language: generic

services: docker

before_install:
  - docker build andrewbalzer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andrewbalzer/react-test npm test

after_success:
  - docker build -t andrewbalzer/multi-client ./client
  - docker build -t andrewbalzer/multi-nginx ./nginx
  - docker build -t andrewbalzer/multi-server ./server
  - docker build -t andrewbalzer/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push andrewbalzer/multi-client
  - docker push andrewbalzer/multi-nginx
  - docker push andrewbalzer/multi-server
  - docker push andrewbalzer/multi-worker
