language: generic

services: docker

before_install:
  - docker build andrewbalzer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true andrewbalzer/react-test npm test -- --coverage

after_success:
  - docker build -t andrewbalzer/multi-client ./client
  - docker build -t andrewbalzer/multi-nginx ./nginx
  - docker build -t andrewbalzer/multi-server ./server
  - docker build -t andrewbalzer/multi-worker ./worker
